### ISSUE TITLE
Schedule a task which repeats every 12 hours at 5:30am & pm?

### ISSUE THREAD

**Issue by MSeneadza** [simplymadeapps/simple_scheduler#17]
Is is possible, which 1 config file entry, to schedule a task which repeats every 12 hours at specific times (like 5:30am and 5:30pm)? I just entered this:

```
reset_cache:
  class: "RefreshCacheWorker"
  every: "12.hours"
  at: "05:30"
  tz: "America/New_York"```

But what I got was that task scheduled twice at 5:30am tomorrow:

```
[ActiveJob] [SimpleScheduler::SchedulerJob] [0ea4ed14-aa7c-4bde-bc1a-b07a2577b75f] Enqueued SimpleScheduler::FutureJob (Job ID: 9b5c4f0c-1a78-49c1-8ad5-7aabad669720) to Sidekiq(default) at 2017-03-30 09:30:00 UTC with arguments: {:class=>"RefreshCacheWorker", :every=>"12.hours", :at=>"05:30", :tz=>"America/New_York", :queue_ahead=>360, :name=>"reset_cache"}, 1490866200
[ActiveJob] [SimpleScheduler::SchedulerJob] [0ea4ed14-aa7c-4bde-bc1a-b07a2577b75f] Enqueued SimpleScheduler::FutureJob (Job ID: cee4d457-fa81-47e8-ad5b-105afe21eaef) to Sidekiq(default) at 2017-03-30 09:30:00 UTC with arguments: {:class=>"RefreshCacheWorker", :every=>"12.hours", :at=>"05:30", :tz=>"America/New_York", :queue_ahead=>360, :name=>"reset_cache"}, 1490866200
```

I know I could easily do what I want with two separate config entries (daily at 5:30am and daily @ 5:30pm) but I just thought I'd ask in case there was a way to do it in one config entry.

Thanks.

**Comment by brianpattison** [comment]
You will have to create two separate entries.

It's good to know how you're thinking about it. It will help us improve the documentation, and I might think about changing the behavior to match what you were expecting. 

When you specify the `:at` time with the hour and minutes, it will only run at the specified time. You have to use `*:30` for it to run at both `5:30` and `17:30`, but if you don't specify the hour, it will run immediately when you deploy. If you deployed at 5:00 or 17:00, it would queue up properly, but I don't think you want to rely on timing it that way.

**Comment by MSeneadza** [comment]
Thanks for the clarification Brian.  I'll just make two entries in the config.

**Comment by brianpattison** [comment]
@MSeneadza Make sure you name the tasks differently. The `reset_cache` key is used to look up existing queued jobs, so you'll need define the tasks with two different names:

```yml
reset_cache_am:
  class: "RefreshCacheWorker"
  every: "1.day"
  at: "05:30"
  tz: "America/New_York"

reset_cache_pm:
  class: "RefreshCacheWorker"
  every: "1.day"
  at: "17:30"
  tz: "America/New_York"
```
