### ISSUE TITLE
Question: Job runs daily rather following the days of the week provided

### ISSUE THREAD

**Issue by ACPK** [simplymadeapps/simple_scheduler#19]
I have the following setup in config/simple_scheduler.rb. We'd like the job to only be run M-F, and tried to configure it using the code below. Do you have any suggestions as it ran today (i.e. Saturday)?

    # Global configuration options. These can also be set on each task.
    queue_ahead: 360 # Number of minutes to queue jobs into the future

    tz: "America/New_York" # The application time zone will be used by default if not set

    # Runs once every day at 4:15 PM. The job will expire after 18 hours, which means the
    # job will not run if 18 hours passes (server downtime) before the job is actually run
    overnight_task:
      class: "DailyJob"
      every: "1.day"
      at: "[Mon|Tue|Wed|Thu|Fri] 20:00"
      expires_after: "23.hours"

**Comment by bmedenwald** [comment]
This is similar to https://github.com/simplymadeapps/simple_scheduler/issues/17 in that we should probably change the documentation to reflect this use case better.  There are two issues at play, one documentation and one a bug it would seem.

The `at` time dictates when this Daily job should start queuing, not only when it should run. For a daily job, adding a day of the week would only postpone the first run, not the subsequent runs. Adding a day of the week works great for weekly jobs. Your example job would run every day at 20:00.  If you pick one day of the week, that will run your daily job starting on that day, but after that it would run every single day per the `every` option.

The second issue is with `[Mon|Tue|Wed|Thu|Fri]`. I can see how the documentation can read that this is valid but in fact it should read that these are the days that are acceptable options, but you should pick one day.  The bug is that this string doesn't raise an `InvalidTime` error, which it should. Of course, we should also update the docs so that this doesn't appear possible right now.

To do what you're after, you'll want to create 5 tasks (name them differently as the `reset_cache` key is used to look up existing queued jobs) that run every `1.week` starting on Mon, Tue, Wed, Thu, and Fri specifically. Like so:

```yaml
overnight_mon_task:
  class: "DailyJob"
  every: "1.week"
  at: "Mon 20:00"
  expires_after: "23.hours"

overnight_tue_task:
  class: "DailyJob"
  every: "1.week"
  at: "Tue 20:00"
  expires_after: "23.hours"

overnight_wed_task:
  class: "DailyJob"
  every: "1.week"
  at: "Wed 20:00"
  expires_after: "23.hours"

overnight_thu_task:
  class: "DailyJob"
  every: "1.week"
  at: "Thu 20:00"
  expires_after: "23.hours"

overnight_fri_task:
  class: "DailyJob"
  every: "1.week"
  at: "Fri 20:00"
  expires_after: "23.hours"
```
