### ISSUE TITLE
Weekly Jobs one day before

### ISSUE THREAD

**Issue by danielmcoelho** [simplymadeapps/simple_scheduler#28]
All my weekly jobs defined on a specific day of the week are queued to 24 hours before. 
E.g.: 
```
queue_ahead: 10
tz: "America/New_York"

weekly_reports:
  class: "WeeklyReportEmailJob"
  every: "1.week"
  at: "Mon 19:00"
```

On sidekiq the arguments are correct, but the scheduled day is Sunday (17 April, in 5 days) instead of Monday (18 April):
![image](https://cloud.githubusercontent.com/assets/1558992/24971885/63b93080-1fb1-11e7-917b-b21d498e3873.png)
Timestamp hovering "5 days" is `2017-04-17T23:00:00Z` which means that the hours is ok (23h UTC = 19h EDT), but the day is not.

Daily Jobs are being scheduled correctly.
Anyone experience the same? They were working correctly last week (or on the week before).
