### ISSUE TITLE
Sidekiq: Custom Queues?

### ISSUE THREAD

**Issue by mackerel** [simplymadeapps/simple_scheduler#40]
Is it possible to indicate the Sidekiq queue? We are using several custom queue names, and I'm seeing that it uses `default` when creating the SK jobs.

**Comment by brianpattison** [comment]
@mackerel There is currently not a supported way to specify the queue for `SimpleScheduler::FutureJob`. You can probably reopen the class in an initializer to specify the queue name, but I do think you should be able to specify the queue name in the config YAML file. 

I don't know if this actually works, but I think it should:

```ruby
# config/initializers/simple_scheduler.rb
SimpleScheduler::FutureJob.class_eval do
  queue_as :custom_queue_name
end
```

That might work for now until we can implement reading the queue name from the config file.

**Comment by mackerel** [comment]
Thanks again for prompt answer. At least I have somewhere to start digging. All the best!

**Comment by brianpattison** [comment]
@mackerel I'm going to leave this open as an enhancement that we will definitely be adding.

**Comment by mackerel** [comment]
@brianpattison Ah, of course, sorry about that. My Github-fu is a bit weak :)

**Comment by brianpattison** [comment]
@mackerel No worries. If you wanted to take a stab at implementing the solution, please feel free. We love pull requests!

The direction I would give you is that the README should be updated to include the queue_name option:

```yml
# Global configuration options. These can also be set on each task.
queue_ahead: 360 # Number of minutes to queue jobs into the future
queue_name: "default" # The Sidekiq queue name used by SimpleScheduler::FutureJob
tz: "America/Chicago" # The application time zone will be used by default if not set
```

The goal for implementation is to get `SimpleScheduler::FutureJob` to pick it up the specified queue name and fall back to `default` if it's not specified. And of course add tests to ensure it is added to the custom queue or the default queue if not specified.
