### ISSUE TITLE
Job not executing

### ISSUE THREAD

**Issue by sqlninja** [simplymadeapps/simple_scheduler#43]
I've ran thru the setup and can see the scheduled jobs in my redis instance, but the code in my job doesn't seem to be executing.

gemfile:
```
...
gem 'redis'
gem 'sidekiq'
gem 'simple_scheduler'
...
```

simple_scheduler.yml:
```
queue_ahead: 360
queue_name: "message_queue"
tz: "America/Chicago"

process_queue:
   class: "MessageQueueJob"
   every: "1.minutes"
```

MessageQueueJob.rb:
```
class MessageQueueJob < ApplicationJob
   def perform(scheduled_time)
      #doing stuff here that should output the scheduled_time
   end
end
```

I also stuck the job code into my own rake task, and it executes fine when called that way...

I have tried the various suggestions for running locally, and have even push to heroku to see if it would ever run, but no dice...

Any guidance is appreciated
