### ISSUE TITLE
Question: Running multiple queues

### ISSUE THREAD

**Issue by sqlninja** [simplymadeapps/simple_scheduler#47]
So I've had simple_scheduler running fine on the default queue for a little bit now, but I have run into an issue that is requiring me to split up so jobs into separate dynos on Heroku...

I am currently trying to get two workers in my procfile running separate sidekiq queues, which I would assume pick up the jobs created by this gem.

Procfile:
```
web: bundle exec puma -C config/puma.rb
critical_worker: bundle exec sidekiq -C config/sidekiq.yml -q critical
worker: bundle exec sidekiq -C config/sidekiq.yml -q default
```

These seem to boot up fine allowing me to have separate dynos on Heroku, but from there things seem to fall apart (at least in my local testing).

I tried setting the queue_name on a specific job in my simpe_scheduler.yml
```
# Global configuration options. The `queue_ahead` and `tz` options can also be set on each task.
queue_ahead: 360 # 6 hours # Number of minutes to queue jobs into the future
queue_name: "default" # The Sidekiq queue name used by SimpleScheduler::FutureJob
tz: "America/Chicago" # The application time zone will be used by default if not set

# Runs once every 1 minutes
process_queue:
  class: "MessageQueueJob"
  every: "1.minutes"
  queue_name: 'critical' #This did not work...

check_media_status:
  class: "MediaStatusUpdaterJob"
  every: "1.minutes"
```

so then I tried splitting the initializer into two files:
`config/simple_scheduler.yml`
&&
`config/critical_scheduler.yml` #This doesn't seem to work either...
I just set the queue_name to 'critical' in the critical_scheduler.

So I guess my question is:
Is it possible to run multiple queues with this gem allowing me to utilize multiple dynos?
